name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Instalar dependências
        run: npm install

      - name: Aplicar migrações
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: npm run migrate

      # (Opcional) Adicionar passo para correr testes
      # - name: Correr testes
      #   run: npm test 